apiVersion: v1
kind: Namespace
metadata:
  name: html-namespaces
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  namespace: html-namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: html-app
  template:
    metadata:
      labels:
        app: html-app
    spec:
      containers:
      - name: html-container
        image: html-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: html-namespace
spec:
  selector:
    app: html-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
